sudo: required
services:
    - docker

before_install:
    - docker build -t lucca1236/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run lucca1236/react-test npm test -- --coverage

after_success:
    - docker build -t lucca1236/multi-client ./client
    - docker build -t lucca1236/multi-nginx ./nginx
    - docker build -t lucca1236/multi-server ./server
    - docker build -t lucca1236/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push lucca1236/multi-client
    - docker push lucca1236/multi-nginx
    - docker push lucca1236/multi-server
    - docker push lucca1236/multi-worker